
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart SonarQube
  become: true
  ansible.builtin.systemd:
    name: sonarqube
    state: restarted
